package com.example.navsight1

import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

/**
 * End-to-end validation against the REAL committed Haifa OSM assets
 * (app/src/main/assets/osm/haifa/ blobs, generated by scripts/build_haifa_assets.py).
 * Proves the data + readers + queries actually work — not just synthetic blobs.
 *
 * Fixtures below are grounded in the committed assets (extracted by reading the
 * blobs back; see the probe in scripts/build_haifa_assets.py provenance). If the
 * assets are regenerated, these self-consistent queries still hold (a road
 * midpoint snaps to a road; a graph edge's endpoints route; a top token geocodes),
 * but the exact coordinates may need refreshing.
 *
 * Skips (assumeTrue) if the assets are absent so a clean checkout without the
 * generated blobs doesn't fail CI.
 */
class OsmRealAssetsTest {

    private fun asset(name: String): File {
        val candidates = listOf(
            File("src/main/assets/osm/haifa/$name"),
            File("app/src/main/assets/osm/haifa/$name"),
            File(System.getProperty("user.dir"), "src/main/assets/osm/haifa/$name"),
            File(System.getProperty("user.dir"), "app/src/main/assets/osm/haifa/$name")
        )
        return candidates.firstOrNull { it.exists() } ?: candidates[0]
    }

    // Roads are no longer embedded (loaded on demand by RoadRegionManager); the
    // dynamic road path is covered by DynamicRoadsParseTest. Only the embedded
    // Israel-wide SEARCH index is validated against real committed data here.

    @Test
    fun `real geocode is Israel-wide and resolves Hebrew queries`() {
        val f = asset("haifa_geocode.bin")
        assumeTrue("real geocode asset present", f.exists())
        val store = GeocodeIndexReader.parse(f.readBytes())
        // Israel-wide index (≈255k places), not just Haifa (~13k).
        assertTrue("expected the Israel-wide place set, got ${store.placeCount}", store.placeCount > 100_000)

        val anchor = 32.80 to 34.99 // Haifa anchor (proximity tiebreak)

        // Haifa still resolves…
        assertTrue("Haifa should resolve", store.geocode("חיפה", anchor.first, anchor.second, 5).isNotEmpty())
        // …AND places across Israel now resolve (the expansion): Jerusalem, Tel Aviv, Eilat.
        assertTrue("Jerusalem should resolve (Israel-wide)", store.geocode("ירושלים", anchor.first, anchor.second, 5).isNotEmpty())
        assertTrue("Tel Aviv should resolve (Israel-wide)", store.geocode("תל אביב", anchor.first, anchor.second, 5).isNotEmpty())
        assertTrue("Eilat should resolve (Israel-wide)", store.geocode("אילת", anchor.first, anchor.second, 5).isNotEmpty())
        // Prefix (autocomplete) still works.
        assertTrue("Hebrew prefix should resolve", store.geocode("חיפ", anchor.first, anchor.second, 5).isNotEmpty())
        // Out-of-corpus query returns nothing (no false hit, no crash).
        assertTrue("nonsense query returns empty", store.geocode("zzqxnotacity", anchor.first, anchor.second, 5).isEmpty())
    }
}
