package com.example.navsight1.ui.theme

// LEGACY: Material3 default palette generated by the Android Studio template.
// Not used at runtime — the active theming is `NavPalette` + `buildNavPalette`
// in `NavSightTheme.kt`, threaded explicitly through every composable.
// `MainActivity.kt:28` calls `MaterialTheme(colorScheme = darkColorScheme())`
// directly without referencing these tokens. Kept commented per
// "comment, don't delete" rule.

/*
import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
*/
