package com.example.navsight1

import android.util.Log
import com.google.android.gms.maps.model.LatLng
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * OfflineGeocoder — fully offline destination search (MAP_MATCHING_PLAN.md §8M
 * Step K-search*). Thin adapter over [OsmDataLayer.geocode] that mirrors the
 * shapes SearchBarUi already used. $0, no key, no network, jamming-immune.
 *
 * Coverage = whatever region is embedded in the geocode blob (generated by
 * scripts/build_haifa_assets.py). v1 ships an Israel-wide place index, so search
 * resolves any named place in Israel — entirely from the on-device data.
 *
 * `resolve` returns the LatLng for a placeId from a cache populated by the most
 * recent `predictions` call (the UI always resolves an id it just listed).
 */
class OfflineGeocoder {

    @Volatile
    private var lastResolved: Map<String, LatLng> = emptyMap()

    suspend fun predictions(query: String, anchor: LatLng?, limit: Int = 6): List<PlacePrediction> =
        withContext(Dispatchers.Default) {
            val layer = OsmDataLayer.instance ?: run {
                Log.w(TAG, "predictions: OsmDataLayer not loaded — no offline search results")
                return@withContext emptyList<PlacePrediction>()
            }
            val (anchorLat, anchorLng) = resolveAnchor(anchor, layer)
            val hits = layer.geocode(query, anchorLat, anchorLng, limit)

            val cache = HashMap<String, LatLng>(hits.size * 2)
            val preds = hits.map { h ->
                val id = h.placeId.toString()
                cache[id] = LatLng(h.lat, h.lng)
                PlacePrediction(
                    placeId = id,
                    primaryText = h.displayName.substringBefore(','),
                    secondaryText = h.displayName.substringAfter(',', "").trim()
                )
            }
            lastResolved = cache
            preds
        }

    suspend fun resolve(placeId: String): LatLng? = withContext(Dispatchers.Default) {
        lastResolved[placeId]
    }

    private fun resolveAnchor(anchor: LatLng?, layer: OsmDataLayer): Pair<Double, Double> {
        if (anchor != null) return anchor.latitude to anchor.longitude
        // No anchor (no GPS yet): rank around the embedded data's bbox centre.
        val bbox = layer.manifest()?.bbox
        return if (bbox != null && bbox.size == 4) {
            (bbox[1] + bbox[3]) * 0.5 to (bbox[0] + bbox[2]) * 0.5
        } else {
            ISRAEL_CENTER_LAT to ISRAEL_CENTER_LNG
        }
    }

    companion object {
        private const val TAG = "OfflineGeocoder"
        private const val ISRAEL_CENTER_LAT = 31.7
        private const val ISRAEL_CENTER_LNG = 35.0
    }
}
